# coding: utf-8

from __future__ import annotations

# flake8: noqa
"""
    Northrays

    Northrays AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: support@northrays.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # import models into model package
    from northrays_api_client.models.account_provider import AccountProvider
    from northrays_api_client.models.admin_create_runner import AdminCreateRunner
    from northrays_api_client.models.admin_get_webhook_status200_response import AdminGetWebhookStatus200Response
    from northrays_api_client.models.announcement import Announcement
    from northrays_api_client.models.api_key_list import ApiKeyList
    from northrays_api_client.models.api_key_response import ApiKeyResponse
    from northrays_api_client.models.audit_log import AuditLog
    from northrays_api_client.models.build_info import BuildInfo
    from northrays_api_client.models.command import Command
    from northrays_api_client.models.completion_context import CompletionContext
    from northrays_api_client.models.completion_item import CompletionItem
    from northrays_api_client.models.completion_list import CompletionList
    from northrays_api_client.models.compressed_screenshot_response import CompressedScreenshotResponse
    from northrays_api_client.models.computer_use_start_response import ComputerUseStartResponse
    from northrays_api_client.models.computer_use_status_response import ComputerUseStatusResponse
    from northrays_api_client.models.computer_use_stop_response import ComputerUseStopResponse
    from northrays_api_client.models.create_api_key import CreateApiKey
    from northrays_api_client.models.create_build_info import CreateBuildInfo
    from northrays_api_client.models.create_docker_registry import CreateDockerRegistry
    from northrays_api_client.models.create_linked_account import CreateLinkedAccount
    from northrays_api_client.models.create_organization import CreateOrganization
    from northrays_api_client.models.create_organization_invitation import CreateOrganizationInvitation
    from northrays_api_client.models.create_organization_quota import CreateOrganizationQuota
    from northrays_api_client.models.create_organization_region_quota import CreateOrganizationRegionQuota
    from northrays_api_client.models.create_organization_role import CreateOrganizationRole
    from northrays_api_client.models.create_region import CreateRegion
    from northrays_api_client.models.create_region_response import CreateRegionResponse
    from northrays_api_client.models.create_runner import CreateRunner
    from northrays_api_client.models.create_runner_response import CreateRunnerResponse
    from northrays_api_client.models.create_sandbox import CreateSandbox
    from northrays_api_client.models.create_sandbox_snapshot import CreateSandboxSnapshot
    from northrays_api_client.models.create_session_request import CreateSessionRequest
    from northrays_api_client.models.create_snapshot import CreateSnapshot
    from northrays_api_client.models.create_user import CreateUser
    from northrays_api_client.models.create_volume import CreateVolume
    from northrays_api_client.models.northrays_configuration import NorthraysConfiguration
    from northrays_api_client.models.display_info_response import DisplayInfoResponse
    from northrays_api_client.models.docker_registry import DockerRegistry
    from northrays_api_client.models.download_files import DownloadFiles
    from northrays_api_client.models.execute_request import ExecuteRequest
    from northrays_api_client.models.execute_response import ExecuteResponse
    from northrays_api_client.models.file_info import FileInfo
    from northrays_api_client.models.file_status import FileStatus
    from northrays_api_client.models.fork_sandbox import ForkSandbox
    from northrays_api_client.models.git_add_request import GitAddRequest
    from northrays_api_client.models.git_branch_request import GitBranchRequest
    from northrays_api_client.models.git_checkout_request import GitCheckoutRequest
    from northrays_api_client.models.git_clone_request import GitCloneRequest
    from northrays_api_client.models.git_commit_info import GitCommitInfo
    from northrays_api_client.models.git_commit_request import GitCommitRequest
    from northrays_api_client.models.git_commit_response import GitCommitResponse
    from northrays_api_client.models.git_delete_branch_request import GitDeleteBranchRequest
    from northrays_api_client.models.git_repo_request import GitRepoRequest
    from northrays_api_client.models.git_status import GitStatus
    from northrays_api_client.models.gpu_type import GpuType
    from northrays_api_client.models.health_controller_check200_response import HealthControllerCheck200Response
    from northrays_api_client.models.health_controller_check200_response_info_value import HealthControllerCheck200ResponseInfoValue
    from northrays_api_client.models.health_controller_check503_response import HealthControllerCheck503Response
    from northrays_api_client.models.job import Job
    from northrays_api_client.models.job_status import JobStatus
    from northrays_api_client.models.job_type import JobType
    from northrays_api_client.models.keyboard_hotkey_request import KeyboardHotkeyRequest
    from northrays_api_client.models.keyboard_press_request import KeyboardPressRequest
    from northrays_api_client.models.keyboard_type_request import KeyboardTypeRequest
    from northrays_api_client.models.list_branch_response import ListBranchResponse
    from northrays_api_client.models.list_sandboxes_response import ListSandboxesResponse
    from northrays_api_client.models.log_entry import LogEntry
    from northrays_api_client.models.lsp_completion_params import LspCompletionParams
    from northrays_api_client.models.lsp_document_request import LspDocumentRequest
    from northrays_api_client.models.lsp_location import LspLocation
    from northrays_api_client.models.lsp_server_request import LspServerRequest
    from northrays_api_client.models.lsp_symbol import LspSymbol
    from northrays_api_client.models.match import Match
    from northrays_api_client.models.metric_data_point import MetricDataPoint
    from northrays_api_client.models.metric_series import MetricSeries
    from northrays_api_client.models.metrics_response import MetricsResponse
    from northrays_api_client.models.mouse_click_request import MouseClickRequest
    from northrays_api_client.models.mouse_click_response import MouseClickResponse
    from northrays_api_client.models.mouse_drag_request import MouseDragRequest
    from northrays_api_client.models.mouse_drag_response import MouseDragResponse
    from northrays_api_client.models.mouse_move_request import MouseMoveRequest
    from northrays_api_client.models.mouse_move_response import MouseMoveResponse
    from northrays_api_client.models.mouse_position import MousePosition
    from northrays_api_client.models.mouse_scroll_request import MouseScrollRequest
    from northrays_api_client.models.mouse_scroll_response import MouseScrollResponse
    from northrays_api_client.models.oidc_config import OidcConfig
    from northrays_api_client.models.organization import Organization
    from northrays_api_client.models.organization_invitation import OrganizationInvitation
    from northrays_api_client.models.organization_role import OrganizationRole
    from northrays_api_client.models.organization_sandbox_default_limited_network_egress import OrganizationSandboxDefaultLimitedNetworkEgress
    from northrays_api_client.models.organization_suspension import OrganizationSuspension
    from northrays_api_client.models.organization_usage_overview import OrganizationUsageOverview
    from northrays_api_client.models.organization_user import OrganizationUser
    from northrays_api_client.models.otel_config import OtelConfig
    from northrays_api_client.models.paginated_audit_logs import PaginatedAuditLogs
    from northrays_api_client.models.paginated_jobs import PaginatedJobs
    from northrays_api_client.models.paginated_logs import PaginatedLogs
    from northrays_api_client.models.paginated_sandboxes_deprecated import PaginatedSandboxesDeprecated
    from northrays_api_client.models.paginated_snapshots import PaginatedSnapshots
    from northrays_api_client.models.paginated_traces import PaginatedTraces
    from northrays_api_client.models.poll_jobs_response import PollJobsResponse
    from northrays_api_client.models.port_preview_url import PortPreviewUrl
    from northrays_api_client.models.position import Position
    from northrays_api_client.models.posthog_config import PosthogConfig
    from northrays_api_client.models.process_errors_response import ProcessErrorsResponse
    from northrays_api_client.models.process_logs_response import ProcessLogsResponse
    from northrays_api_client.models.process_restart_response import ProcessRestartResponse
    from northrays_api_client.models.process_status_response import ProcessStatusResponse
    from northrays_api_client.models.project_dir_response import ProjectDirResponse
    from northrays_api_client.models.pty_create_request import PtyCreateRequest
    from northrays_api_client.models.pty_create_response import PtyCreateResponse
    from northrays_api_client.models.pty_list_response import PtyListResponse
    from northrays_api_client.models.pty_resize_request import PtyResizeRequest
    from northrays_api_client.models.pty_session_info import PtySessionInfo
    from northrays_api_client.models.range import Range
    from northrays_api_client.models.rate_limit_config import RateLimitConfig
    from northrays_api_client.models.rate_limit_entry import RateLimitEntry
    from northrays_api_client.models.regenerate_api_key_response import RegenerateApiKeyResponse
    from northrays_api_client.models.region import Region
    from northrays_api_client.models.region_quota import RegionQuota
    from northrays_api_client.models.region_screenshot_response import RegionScreenshotResponse
    from northrays_api_client.models.region_type import RegionType
    from northrays_api_client.models.region_usage_overview import RegionUsageOverview
    from northrays_api_client.models.registry_push_access_dto import RegistryPushAccessDto
    from northrays_api_client.models.replace_request import ReplaceRequest
    from northrays_api_client.models.replace_result import ReplaceResult
    from northrays_api_client.models.resize_sandbox import ResizeSandbox
    from northrays_api_client.models.runner import Runner
    from northrays_api_client.models.runner_class import RunnerClass
    from northrays_api_client.models.runner_full import RunnerFull
    from northrays_api_client.models.runner_health_metrics import RunnerHealthMetrics
    from northrays_api_client.models.runner_healthcheck import RunnerHealthcheck
    from northrays_api_client.models.runner_service_health import RunnerServiceHealth
    from northrays_api_client.models.runner_snapshot_dto import RunnerSnapshotDto
    from northrays_api_client.models.runner_state import RunnerState
    from northrays_api_client.models.sandbox import Sandbox
    from northrays_api_client.models.sandbox_class import SandboxClass
    from northrays_api_client.models.sandbox_desired_state import SandboxDesiredState
    from northrays_api_client.models.sandbox_labels import SandboxLabels
    from northrays_api_client.models.sandbox_list_item import SandboxListItem
    from northrays_api_client.models.sandbox_list_sort_direction import SandboxListSortDirection
    from northrays_api_client.models.sandbox_list_sort_field import SandboxListSortField
    from northrays_api_client.models.sandbox_state import SandboxState
    from northrays_api_client.models.sandbox_volume import SandboxVolume
    from northrays_api_client.models.screenshot_response import ScreenshotResponse
    from northrays_api_client.models.search_files_response import SearchFilesResponse
    from northrays_api_client.models.send_webhook_dto import SendWebhookDto
    from northrays_api_client.models.session import Session
    from northrays_api_client.models.session_execute_request import SessionExecuteRequest
    from northrays_api_client.models.session_execute_response import SessionExecuteResponse
    from northrays_api_client.models.set_snapshot_general_status_dto import SetSnapshotGeneralStatusDto
    from northrays_api_client.models.signed_port_preview_url import SignedPortPreviewUrl
    from northrays_api_client.models.snapshot_dto import SnapshotDto
    from northrays_api_client.models.snapshot_manager_credentials import SnapshotManagerCredentials
    from northrays_api_client.models.snapshot_state import SnapshotState
    from northrays_api_client.models.ssh_access_dto import SshAccessDto
    from northrays_api_client.models.ssh_access_validation_dto import SshAccessValidationDto
    from northrays_api_client.models.storage_access_dto import StorageAccessDto
    from northrays_api_client.models.toolbox_proxy_url import ToolboxProxyUrl
    from northrays_api_client.models.trace_span import TraceSpan
    from northrays_api_client.models.trace_summary import TraceSummary
    from northrays_api_client.models.update_docker_registry import UpdateDockerRegistry
    from northrays_api_client.models.update_job_status import UpdateJobStatus
    from northrays_api_client.models.update_organization_default_region import UpdateOrganizationDefaultRegion
    from northrays_api_client.models.update_organization_invitation import UpdateOrganizationInvitation
    from northrays_api_client.models.update_organization_member_access import UpdateOrganizationMemberAccess
    from northrays_api_client.models.update_organization_quota import UpdateOrganizationQuota
    from northrays_api_client.models.update_organization_region_quota import UpdateOrganizationRegionQuota
    from northrays_api_client.models.update_organization_role import UpdateOrganizationRole
    from northrays_api_client.models.update_region import UpdateRegion
    from northrays_api_client.models.update_sandbox_network_settings import UpdateSandboxNetworkSettings
    from northrays_api_client.models.update_sandbox_state_dto import UpdateSandboxStateDto
    from northrays_api_client.models.url import Url
    from northrays_api_client.models.user import User
    from northrays_api_client.models.user_home_dir_response import UserHomeDirResponse
    from northrays_api_client.models.user_public_key import UserPublicKey
    from northrays_api_client.models.volume_dto import VolumeDto
    from northrays_api_client.models.volume_state import VolumeState
    from northrays_api_client.models.webhook_app_portal_access import WebhookAppPortalAccess
    from northrays_api_client.models.webhook_event import WebhookEvent
    from northrays_api_client.models.webhook_initialization_status import WebhookInitializationStatus
    from northrays_api_client.models.windows_response import WindowsResponse
    from northrays_api_client.models.work_dir_response import WorkDirResponse

_DYNAMIC_IMPORTS: dict[str, str] = {
    "AccountProvider": "northrays_api_client.models.account_provider",
    "AdminCreateRunner": "northrays_api_client.models.admin_create_runner",
    "AdminGetWebhookStatus200Response": "northrays_api_client.models.admin_get_webhook_status200_response",
    "Announcement": "northrays_api_client.models.announcement",
    "ApiKeyList": "northrays_api_client.models.api_key_list",
    "ApiKeyResponse": "northrays_api_client.models.api_key_response",
    "AuditLog": "northrays_api_client.models.audit_log",
    "BuildInfo": "northrays_api_client.models.build_info",
    "Command": "northrays_api_client.models.command",
    "CompletionContext": "northrays_api_client.models.completion_context",
    "CompletionItem": "northrays_api_client.models.completion_item",
    "CompletionList": "northrays_api_client.models.completion_list",
    "CompressedScreenshotResponse": "northrays_api_client.models.compressed_screenshot_response",
    "ComputerUseStartResponse": "northrays_api_client.models.computer_use_start_response",
    "ComputerUseStatusResponse": "northrays_api_client.models.computer_use_status_response",
    "ComputerUseStopResponse": "northrays_api_client.models.computer_use_stop_response",
    "CreateApiKey": "northrays_api_client.models.create_api_key",
    "CreateBuildInfo": "northrays_api_client.models.create_build_info",
    "CreateDockerRegistry": "northrays_api_client.models.create_docker_registry",
    "CreateLinkedAccount": "northrays_api_client.models.create_linked_account",
    "CreateOrganization": "northrays_api_client.models.create_organization",
    "CreateOrganizationInvitation": "northrays_api_client.models.create_organization_invitation",
    "CreateOrganizationQuota": "northrays_api_client.models.create_organization_quota",
    "CreateOrganizationRegionQuota": "northrays_api_client.models.create_organization_region_quota",
    "CreateOrganizationRole": "northrays_api_client.models.create_organization_role",
    "CreateRegion": "northrays_api_client.models.create_region",
    "CreateRegionResponse": "northrays_api_client.models.create_region_response",
    "CreateRunner": "northrays_api_client.models.create_runner",
    "CreateRunnerResponse": "northrays_api_client.models.create_runner_response",
    "CreateSandbox": "northrays_api_client.models.create_sandbox",
    "CreateSandboxSnapshot": "northrays_api_client.models.create_sandbox_snapshot",
    "CreateSessionRequest": "northrays_api_client.models.create_session_request",
    "CreateSnapshot": "northrays_api_client.models.create_snapshot",
    "CreateUser": "northrays_api_client.models.create_user",
    "CreateVolume": "northrays_api_client.models.create_volume",
    "NorthraysConfiguration": "northrays_api_client.models.northrays_configuration",
    "DisplayInfoResponse": "northrays_api_client.models.display_info_response",
    "DockerRegistry": "northrays_api_client.models.docker_registry",
    "DownloadFiles": "northrays_api_client.models.download_files",
    "ExecuteRequest": "northrays_api_client.models.execute_request",
    "ExecuteResponse": "northrays_api_client.models.execute_response",
    "FileInfo": "northrays_api_client.models.file_info",
    "FileStatus": "northrays_api_client.models.file_status",
    "ForkSandbox": "northrays_api_client.models.fork_sandbox",
    "GitAddRequest": "northrays_api_client.models.git_add_request",
    "GitBranchRequest": "northrays_api_client.models.git_branch_request",
    "GitCheckoutRequest": "northrays_api_client.models.git_checkout_request",
    "GitCloneRequest": "northrays_api_client.models.git_clone_request",
    "GitCommitInfo": "northrays_api_client.models.git_commit_info",
    "GitCommitRequest": "northrays_api_client.models.git_commit_request",
    "GitCommitResponse": "northrays_api_client.models.git_commit_response",
    "GitDeleteBranchRequest": "northrays_api_client.models.git_delete_branch_request",
    "GitRepoRequest": "northrays_api_client.models.git_repo_request",
    "GitStatus": "northrays_api_client.models.git_status",
    "GpuType": "northrays_api_client.models.gpu_type",
    "HealthControllerCheck200Response": "northrays_api_client.models.health_controller_check200_response",
    "HealthControllerCheck200ResponseInfoValue": "northrays_api_client.models.health_controller_check200_response_info_value",
    "HealthControllerCheck503Response": "northrays_api_client.models.health_controller_check503_response",
    "Job": "northrays_api_client.models.job",
    "JobStatus": "northrays_api_client.models.job_status",
    "JobType": "northrays_api_client.models.job_type",
    "KeyboardHotkeyRequest": "northrays_api_client.models.keyboard_hotkey_request",
    "KeyboardPressRequest": "northrays_api_client.models.keyboard_press_request",
    "KeyboardTypeRequest": "northrays_api_client.models.keyboard_type_request",
    "ListBranchResponse": "northrays_api_client.models.list_branch_response",
    "ListSandboxesResponse": "northrays_api_client.models.list_sandboxes_response",
    "LogEntry": "northrays_api_client.models.log_entry",
    "LspCompletionParams": "northrays_api_client.models.lsp_completion_params",
    "LspDocumentRequest": "northrays_api_client.models.lsp_document_request",
    "LspLocation": "northrays_api_client.models.lsp_location",
    "LspServerRequest": "northrays_api_client.models.lsp_server_request",
    "LspSymbol": "northrays_api_client.models.lsp_symbol",
    "Match": "northrays_api_client.models.match",
    "MetricDataPoint": "northrays_api_client.models.metric_data_point",
    "MetricSeries": "northrays_api_client.models.metric_series",
    "MetricsResponse": "northrays_api_client.models.metrics_response",
    "MouseClickRequest": "northrays_api_client.models.mouse_click_request",
    "MouseClickResponse": "northrays_api_client.models.mouse_click_response",
    "MouseDragRequest": "northrays_api_client.models.mouse_drag_request",
    "MouseDragResponse": "northrays_api_client.models.mouse_drag_response",
    "MouseMoveRequest": "northrays_api_client.models.mouse_move_request",
    "MouseMoveResponse": "northrays_api_client.models.mouse_move_response",
    "MousePosition": "northrays_api_client.models.mouse_position",
    "MouseScrollRequest": "northrays_api_client.models.mouse_scroll_request",
    "MouseScrollResponse": "northrays_api_client.models.mouse_scroll_response",
    "OidcConfig": "northrays_api_client.models.oidc_config",
    "Organization": "northrays_api_client.models.organization",
    "OrganizationInvitation": "northrays_api_client.models.organization_invitation",
    "OrganizationRole": "northrays_api_client.models.organization_role",
    "OrganizationSandboxDefaultLimitedNetworkEgress": "northrays_api_client.models.organization_sandbox_default_limited_network_egress",
    "OrganizationSuspension": "northrays_api_client.models.organization_suspension",
    "OrganizationUsageOverview": "northrays_api_client.models.organization_usage_overview",
    "OrganizationUser": "northrays_api_client.models.organization_user",
    "OtelConfig": "northrays_api_client.models.otel_config",
    "PaginatedAuditLogs": "northrays_api_client.models.paginated_audit_logs",
    "PaginatedJobs": "northrays_api_client.models.paginated_jobs",
    "PaginatedLogs": "northrays_api_client.models.paginated_logs",
    "PaginatedSandboxesDeprecated": "northrays_api_client.models.paginated_sandboxes_deprecated",
    "PaginatedSnapshots": "northrays_api_client.models.paginated_snapshots",
    "PaginatedTraces": "northrays_api_client.models.paginated_traces",
    "PollJobsResponse": "northrays_api_client.models.poll_jobs_response",
    "PortPreviewUrl": "northrays_api_client.models.port_preview_url",
    "Position": "northrays_api_client.models.position",
    "PosthogConfig": "northrays_api_client.models.posthog_config",
    "ProcessErrorsResponse": "northrays_api_client.models.process_errors_response",
    "ProcessLogsResponse": "northrays_api_client.models.process_logs_response",
    "ProcessRestartResponse": "northrays_api_client.models.process_restart_response",
    "ProcessStatusResponse": "northrays_api_client.models.process_status_response",
    "ProjectDirResponse": "northrays_api_client.models.project_dir_response",
    "PtyCreateRequest": "northrays_api_client.models.pty_create_request",
    "PtyCreateResponse": "northrays_api_client.models.pty_create_response",
    "PtyListResponse": "northrays_api_client.models.pty_list_response",
    "PtyResizeRequest": "northrays_api_client.models.pty_resize_request",
    "PtySessionInfo": "northrays_api_client.models.pty_session_info",
    "Range": "northrays_api_client.models.range",
    "RateLimitConfig": "northrays_api_client.models.rate_limit_config",
    "RateLimitEntry": "northrays_api_client.models.rate_limit_entry",
    "RegenerateApiKeyResponse": "northrays_api_client.models.regenerate_api_key_response",
    "Region": "northrays_api_client.models.region",
    "RegionQuota": "northrays_api_client.models.region_quota",
    "RegionScreenshotResponse": "northrays_api_client.models.region_screenshot_response",
    "RegionType": "northrays_api_client.models.region_type",
    "RegionUsageOverview": "northrays_api_client.models.region_usage_overview",
    "RegistryPushAccessDto": "northrays_api_client.models.registry_push_access_dto",
    "ReplaceRequest": "northrays_api_client.models.replace_request",
    "ReplaceResult": "northrays_api_client.models.replace_result",
    "ResizeSandbox": "northrays_api_client.models.resize_sandbox",
    "Runner": "northrays_api_client.models.runner",
    "RunnerClass": "northrays_api_client.models.runner_class",
    "RunnerFull": "northrays_api_client.models.runner_full",
    "RunnerHealthMetrics": "northrays_api_client.models.runner_health_metrics",
    "RunnerHealthcheck": "northrays_api_client.models.runner_healthcheck",
    "RunnerServiceHealth": "northrays_api_client.models.runner_service_health",
    "RunnerSnapshotDto": "northrays_api_client.models.runner_snapshot_dto",
    "RunnerState": "northrays_api_client.models.runner_state",
    "Sandbox": "northrays_api_client.models.sandbox",
    "SandboxClass": "northrays_api_client.models.sandbox_class",
    "SandboxDesiredState": "northrays_api_client.models.sandbox_desired_state",
    "SandboxLabels": "northrays_api_client.models.sandbox_labels",
    "SandboxListItem": "northrays_api_client.models.sandbox_list_item",
    "SandboxListSortDirection": "northrays_api_client.models.sandbox_list_sort_direction",
    "SandboxListSortField": "northrays_api_client.models.sandbox_list_sort_field",
    "SandboxState": "northrays_api_client.models.sandbox_state",
    "SandboxVolume": "northrays_api_client.models.sandbox_volume",
    "ScreenshotResponse": "northrays_api_client.models.screenshot_response",
    "SearchFilesResponse": "northrays_api_client.models.search_files_response",
    "SendWebhookDto": "northrays_api_client.models.send_webhook_dto",
    "Session": "northrays_api_client.models.session",
    "SessionExecuteRequest": "northrays_api_client.models.session_execute_request",
    "SessionExecuteResponse": "northrays_api_client.models.session_execute_response",
    "SetSnapshotGeneralStatusDto": "northrays_api_client.models.set_snapshot_general_status_dto",
    "SignedPortPreviewUrl": "northrays_api_client.models.signed_port_preview_url",
    "SnapshotDto": "northrays_api_client.models.snapshot_dto",
    "SnapshotManagerCredentials": "northrays_api_client.models.snapshot_manager_credentials",
    "SnapshotState": "northrays_api_client.models.snapshot_state",
    "SshAccessDto": "northrays_api_client.models.ssh_access_dto",
    "SshAccessValidationDto": "northrays_api_client.models.ssh_access_validation_dto",
    "StorageAccessDto": "northrays_api_client.models.storage_access_dto",
    "ToolboxProxyUrl": "northrays_api_client.models.toolbox_proxy_url",
    "TraceSpan": "northrays_api_client.models.trace_span",
    "TraceSummary": "northrays_api_client.models.trace_summary",
    "UpdateDockerRegistry": "northrays_api_client.models.update_docker_registry",
    "UpdateJobStatus": "northrays_api_client.models.update_job_status",
    "UpdateOrganizationDefaultRegion": "northrays_api_client.models.update_organization_default_region",
    "UpdateOrganizationInvitation": "northrays_api_client.models.update_organization_invitation",
    "UpdateOrganizationMemberAccess": "northrays_api_client.models.update_organization_member_access",
    "UpdateOrganizationQuota": "northrays_api_client.models.update_organization_quota",
    "UpdateOrganizationRegionQuota": "northrays_api_client.models.update_organization_region_quota",
    "UpdateOrganizationRole": "northrays_api_client.models.update_organization_role",
    "UpdateRegion": "northrays_api_client.models.update_region",
    "UpdateSandboxNetworkSettings": "northrays_api_client.models.update_sandbox_network_settings",
    "UpdateSandboxStateDto": "northrays_api_client.models.update_sandbox_state_dto",
    "Url": "northrays_api_client.models.url",
    "User": "northrays_api_client.models.user",
    "UserHomeDirResponse": "northrays_api_client.models.user_home_dir_response",
    "UserPublicKey": "northrays_api_client.models.user_public_key",
    "VolumeDto": "northrays_api_client.models.volume_dto",
    "VolumeState": "northrays_api_client.models.volume_state",
    "WebhookAppPortalAccess": "northrays_api_client.models.webhook_app_portal_access",
    "WebhookEvent": "northrays_api_client.models.webhook_event",
    "WebhookInitializationStatus": "northrays_api_client.models.webhook_initialization_status",
    "WindowsResponse": "northrays_api_client.models.windows_response",
    "WorkDirResponse": "northrays_api_client.models.work_dir_response",
}


def __getattr__(attr_name: str) -> object:
    module_path = _DYNAMIC_IMPORTS.get(attr_name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")
    mod = importlib.import_module(module_path)
    value = getattr(mod, attr_name)
    globals()[attr_name] = value
    return value


def __dir__() -> list[str]:
    return list(_DYNAMIC_IMPORTS.keys())
