=begin
#Northrays

#Northrays AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: support@northrays.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

module NorthraysApiClient
  VERSION = '0.0.0.pre.dev'
end
