/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Runner API
 * Northrays Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DtoVolumeDTO } from './dto-volume-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RegistryDTO } from './registry-dto';

export interface CreateSandboxDTO {
    'authToken'?: string;
    /**
     * BrowserSandbox says this sandbox runs a browser that sandboxes itself.  Sent explicitly by the caller rather than inferred. The computer-use plugin is mounted into every sandbox, so its presence says nothing about whether a browser will run -- inferring from it would widen the syscall filter for workloads that never launch one.  It is also NOT the same question as SandboxClass, which describes the shape of the machine (container, linux-vm, android, windows). This describes the workload, and the two vary independently.  Its only effect is the seccomp profile: see browserSeccompProfile. Everything else about a restricted sandbox -- unprivileged, capabilities dropped, egress enforced -- is unchanged, and a browser sandbox that is NOT restricted gets nothing extra.
     */
    'browserSandbox'?: boolean;
    'cpuQuota'?: number;
    'domainAllowList'?: string;
    'entrypoint'?: Array<string>;
    'env'?: { [key: string]: string; };
    'fromVolumeId'?: string;
    'gpuQuota'?: number;
    'id': string;
    /**
     * LinkedSandboxId identifies an existing sandbox this sandbox should be co-located with. When set, the runner should attach both sandboxes to a shared local network so they can communicate.
     */
    'linkedSandboxId'?: string;
    'memoryQuota'?: number;
    'metadata'?: { [key: string]: string; };
    /**
     * Name is the human-readable sandbox name. When present, it is used as the network alias for link networks so linked sandboxes can resolve each other by name.
     */
    'name'?: string;
    'networkAllowList'?: string;
    'networkBlockAll'?: boolean;
    /**
     * Nullable for backward compatibility
     */
    'organizationId'?: string;
    'osUser': string;
    'otelEndpoint'?: string;
    'regionId'?: string;
    'registry'?: RegistryDTO;
    /**
     * Optional for backward compatibility, but when provided, indicates the class of sandbox to create.
     */
    'sandboxClass'?: string;
    'skipStart'?: boolean;
    'snapshot': string;
    'storageQuota'?: number;
    'userId': string;
    'volumes'?: Array<DtoVolumeDTO>;
}

