/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Runner API
 * Northrays Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnapshotExistsResponse {
    'exists'?: boolean;
}

