# -*- encoding: utf-8 -*-

=begin
#Northrays

#Northrays AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: support@northrays.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "northrays_api_client/version"

Gem::Specification.new do |s|
  s.name        = "northrays_api_client"
  s.version     = NorthraysApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["northrays"]
  s.email       = ["support@northrays.com"]
  s.homepage    = "https://github.com/northrays/sandbox-platform"
  s.summary     = "Northrays Ruby Gem"
  s.description = "Northrays API Client"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) || f.end_with?('.gem') || f.start_with?('Gemfile') }
  s.test_files    = Dir.exist?('spec') ? Dir.glob('spec/**/*') : []
  s.executables   = []
  s.require_paths = ["lib"]
end
