/*
 * Northrays
 * Northrays AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@northrays.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.api.client.api;

import io.northrays.api.client.ApiCallback;
import io.northrays.api.client.ApiClient;
import io.northrays.api.client.ApiException;
import io.northrays.api.client.ApiResponse;
import io.northrays.api.client.Configuration;
import io.northrays.api.client.Pair;
import io.northrays.api.client.ProgressRequestBody;
import io.northrays.api.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.northrays.api.client.model.CreateRunner;
import io.northrays.api.client.model.CreateRunnerResponse;
import io.northrays.api.client.model.Runner;
import io.northrays.api.client.model.RunnerFull;
import io.northrays.api.client.model.RunnerHealthcheck;
import io.northrays.api.client.model.RunnerSnapshotDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RunnersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RunnersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RunnersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createRunner
     * @param createRunner  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRunnerCall(@javax.annotation.Nonnull CreateRunner createRunner, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createRunner;

        // create path and map variables
        String localVarPath = "/runners";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRunnerValidateBeforeCall(@javax.annotation.Nonnull CreateRunner createRunner, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createRunner' is set
        if (createRunner == null) {
            throw new ApiException("Missing the required parameter 'createRunner' when calling createRunner(Async)");
        }

        return createRunnerCall(createRunner, xNorthraysOrganizationID, _callback);

    }

    /**
     * Create runner
     * 
     * @param createRunner  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return CreateRunnerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public CreateRunnerResponse createRunner(@javax.annotation.Nonnull CreateRunner createRunner, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<CreateRunnerResponse> localVarResp = createRunnerWithHttpInfo(createRunner, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Create runner
     * 
     * @param createRunner  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;CreateRunnerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateRunnerResponse> createRunnerWithHttpInfo(@javax.annotation.Nonnull CreateRunner createRunner, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = createRunnerValidateBeforeCall(createRunner, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<CreateRunnerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create runner (asynchronously)
     * 
     * @param createRunner  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRunnerAsync(@javax.annotation.Nonnull CreateRunner createRunner, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<CreateRunnerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRunnerValidateBeforeCall(createRunner, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<CreateRunnerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteRunner
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRunnerCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteRunnerValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteRunner(Async)");
        }

        return deleteRunnerCall(id, xNorthraysOrganizationID, _callback);

    }

    /**
     * Delete runner
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public void deleteRunner(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        deleteRunnerWithHttpInfo(id, xNorthraysOrganizationID);
    }

    /**
     * Delete runner
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteRunnerWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = deleteRunnerValidateBeforeCall(id, xNorthraysOrganizationID, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete runner (asynchronously)
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRunnerAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteRunnerValidateBeforeCall(id, xNorthraysOrganizationID, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getInfoForAuthenticatedRunner
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Runner info </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInfoForAuthenticatedRunnerCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/me";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInfoForAuthenticatedRunnerValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getInfoForAuthenticatedRunnerCall(_callback);

    }

    /**
     * Get info for authenticated runner
     * 
     * @return RunnerFull
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Runner info </td><td>  -  </td></tr>
     </table>
     */
    public RunnerFull getInfoForAuthenticatedRunner() throws ApiException {
        ApiResponse<RunnerFull> localVarResp = getInfoForAuthenticatedRunnerWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get info for authenticated runner
     * 
     * @return ApiResponse&lt;RunnerFull&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Runner info </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RunnerFull> getInfoForAuthenticatedRunnerWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getInfoForAuthenticatedRunnerValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get info for authenticated runner (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Runner info </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInfoForAuthenticatedRunnerAsync(final ApiCallback<RunnerFull> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInfoForAuthenticatedRunnerValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRunnerById
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerByIdCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRunnerByIdValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRunnerById(Async)");
        }

        return getRunnerByIdCall(id, xNorthraysOrganizationID, _callback);

    }

    /**
     * Get runner by ID
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return Runner
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public Runner getRunnerById(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<Runner> localVarResp = getRunnerByIdWithHttpInfo(id, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Get runner by ID
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;Runner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Runner> getRunnerByIdWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = getRunnerByIdValidateBeforeCall(id, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get runner by ID (asynchronously)
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerByIdAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<Runner> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRunnerByIdValidateBeforeCall(id, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRunnerBySandboxId
     * @param sandboxId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerBySandboxIdCall(@javax.annotation.Nonnull String sandboxId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/by-sandbox/{sandboxId}"
            .replace("{" + "sandboxId" + "}", localVarApiClient.escapeString(sandboxId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRunnerBySandboxIdValidateBeforeCall(@javax.annotation.Nonnull String sandboxId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sandboxId' is set
        if (sandboxId == null) {
            throw new ApiException("Missing the required parameter 'sandboxId' when calling getRunnerBySandboxId(Async)");
        }

        return getRunnerBySandboxIdCall(sandboxId, _callback);

    }

    /**
     * Get runner by sandbox ID
     * 
     * @param sandboxId  (required)
     * @return RunnerFull
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public RunnerFull getRunnerBySandboxId(@javax.annotation.Nonnull String sandboxId) throws ApiException {
        ApiResponse<RunnerFull> localVarResp = getRunnerBySandboxIdWithHttpInfo(sandboxId);
        return localVarResp.getData();
    }

    /**
     * Get runner by sandbox ID
     * 
     * @param sandboxId  (required)
     * @return ApiResponse&lt;RunnerFull&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RunnerFull> getRunnerBySandboxIdWithHttpInfo(@javax.annotation.Nonnull String sandboxId) throws ApiException {
        okhttp3.Call localVarCall = getRunnerBySandboxIdValidateBeforeCall(sandboxId, null);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get runner by sandbox ID (asynchronously)
     * 
     * @param sandboxId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerBySandboxIdAsync(@javax.annotation.Nonnull String sandboxId, final ApiCallback<RunnerFull> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRunnerBySandboxIdValidateBeforeCall(sandboxId, _callback);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRunnerFullById
     * @param id Runner ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerFullByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/{id}/full"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRunnerFullByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRunnerFullById(Async)");
        }

        return getRunnerFullByIdCall(id, _callback);

    }

    /**
     * Get runner by ID
     * 
     * @param id Runner ID (required)
     * @return RunnerFull
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public RunnerFull getRunnerFullById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<RunnerFull> localVarResp = getRunnerFullByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get runner by ID
     * 
     * @param id Runner ID (required)
     * @return ApiResponse&lt;RunnerFull&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RunnerFull> getRunnerFullByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getRunnerFullByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get runner by ID (asynchronously)
     * 
     * @param id Runner ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnerFullByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<RunnerFull> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRunnerFullByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<RunnerFull>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRunnersBySnapshotRef
     * @param ref Snapshot ref (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnersBySnapshotRefCall(@javax.annotation.Nonnull String ref, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/by-snapshot-ref";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (ref != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("ref", ref));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRunnersBySnapshotRefValidateBeforeCall(@javax.annotation.Nonnull String ref, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ref' is set
        if (ref == null) {
            throw new ApiException("Missing the required parameter 'ref' when calling getRunnersBySnapshotRef(Async)");
        }

        return getRunnersBySnapshotRefCall(ref, _callback);

    }

    /**
     * Get runners by snapshot ref
     * 
     * @param ref Snapshot ref (required)
     * @return List&lt;RunnerSnapshotDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public List<RunnerSnapshotDto> getRunnersBySnapshotRef(@javax.annotation.Nonnull String ref) throws ApiException {
        ApiResponse<List<RunnerSnapshotDto>> localVarResp = getRunnersBySnapshotRefWithHttpInfo(ref);
        return localVarResp.getData();
    }

    /**
     * Get runners by snapshot ref
     * 
     * @param ref Snapshot ref (required)
     * @return ApiResponse&lt;List&lt;RunnerSnapshotDto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<RunnerSnapshotDto>> getRunnersBySnapshotRefWithHttpInfo(@javax.annotation.Nonnull String ref) throws ApiException {
        okhttp3.Call localVarCall = getRunnersBySnapshotRefValidateBeforeCall(ref, null);
        Type localVarReturnType = new TypeToken<List<RunnerSnapshotDto>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get runners by snapshot ref (asynchronously)
     * 
     * @param ref Snapshot ref (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRunnersBySnapshotRefAsync(@javax.annotation.Nonnull String ref, final ApiCallback<List<RunnerSnapshotDto>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRunnersBySnapshotRefValidateBeforeCall(ref, _callback);
        Type localVarReturnType = new TypeToken<List<RunnerSnapshotDto>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listRunners
     * @param regionId Filter runners by region ID (optional)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRunnersCall(@javax.annotation.Nullable String regionId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (regionId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("regionId", regionId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listRunnersValidateBeforeCall(@javax.annotation.Nullable String regionId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        return listRunnersCall(regionId, xNorthraysOrganizationID, _callback);

    }

    /**
     * List all runners
     * 
     * @param regionId Filter runners by region ID (optional)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return List&lt;Runner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public List<Runner> listRunners(@javax.annotation.Nullable String regionId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<List<Runner>> localVarResp = listRunnersWithHttpInfo(regionId, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * List all runners
     * 
     * @param regionId Filter runners by region ID (optional)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;List&lt;Runner&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Runner>> listRunnersWithHttpInfo(@javax.annotation.Nullable String regionId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = listRunnersValidateBeforeCall(regionId, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<List<Runner>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all runners (asynchronously)
     * 
     * @param regionId Filter runners by region ID (optional)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listRunnersAsync(@javax.annotation.Nullable String regionId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<List<Runner>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listRunnersValidateBeforeCall(regionId, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<List<Runner>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for runnerHealthcheck
     * @param runnerHealthcheck  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Healthcheck received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call runnerHealthcheckCall(@javax.annotation.Nonnull RunnerHealthcheck runnerHealthcheck, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = runnerHealthcheck;

        // create path and map variables
        String localVarPath = "/runners/healthcheck";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call runnerHealthcheckValidateBeforeCall(@javax.annotation.Nonnull RunnerHealthcheck runnerHealthcheck, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'runnerHealthcheck' is set
        if (runnerHealthcheck == null) {
            throw new ApiException("Missing the required parameter 'runnerHealthcheck' when calling runnerHealthcheck(Async)");
        }

        return runnerHealthcheckCall(runnerHealthcheck, _callback);

    }

    /**
     * Runner healthcheck
     * Endpoint for version 2 runners to send healthcheck and metrics. Updates lastChecked timestamp and runner metrics.
     * @param runnerHealthcheck  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Healthcheck received </td><td>  -  </td></tr>
     </table>
     */
    public void runnerHealthcheck(@javax.annotation.Nonnull RunnerHealthcheck runnerHealthcheck) throws ApiException {
        runnerHealthcheckWithHttpInfo(runnerHealthcheck);
    }

    /**
     * Runner healthcheck
     * Endpoint for version 2 runners to send healthcheck and metrics. Updates lastChecked timestamp and runner metrics.
     * @param runnerHealthcheck  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Healthcheck received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> runnerHealthcheckWithHttpInfo(@javax.annotation.Nonnull RunnerHealthcheck runnerHealthcheck) throws ApiException {
        okhttp3.Call localVarCall = runnerHealthcheckValidateBeforeCall(runnerHealthcheck, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Runner healthcheck (asynchronously)
     * Endpoint for version 2 runners to send healthcheck and metrics. Updates lastChecked timestamp and runner metrics.
     * @param runnerHealthcheck  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Healthcheck received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call runnerHealthcheckAsync(@javax.annotation.Nonnull RunnerHealthcheck runnerHealthcheck, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = runnerHealthcheckValidateBeforeCall(runnerHealthcheck, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRunnerDraining
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRunnerDrainingCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/{id}/draining"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRunnerDrainingValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateRunnerDraining(Async)");
        }

        return updateRunnerDrainingCall(id, xNorthraysOrganizationID, _callback);

    }

    /**
     * Update runner draining status
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return Runner
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public Runner updateRunnerDraining(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<Runner> localVarResp = updateRunnerDrainingWithHttpInfo(id, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Update runner draining status
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;Runner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Runner> updateRunnerDrainingWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = updateRunnerDrainingValidateBeforeCall(id, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update runner draining status (asynchronously)
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRunnerDrainingAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<Runner> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRunnerDrainingValidateBeforeCall(id, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRunnerScheduling
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRunnerSchedulingCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/runners/{id}/scheduling"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRunnerSchedulingValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateRunnerScheduling(Async)");
        }

        return updateRunnerSchedulingCall(id, xNorthraysOrganizationID, _callback);

    }

    /**
     * Update runner scheduling status
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return Runner
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public Runner updateRunnerScheduling(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<Runner> localVarResp = updateRunnerSchedulingWithHttpInfo(id, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Update runner scheduling status
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;Runner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Runner> updateRunnerSchedulingWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = updateRunnerSchedulingValidateBeforeCall(id, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update runner scheduling status (asynchronously)
     * 
     * @param id Runner ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRunnerSchedulingAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<Runner> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRunnerSchedulingValidateBeforeCall(id, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<Runner>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
