/*
 * Northrays
 * Northrays AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@northrays.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.api.client.api;

import io.northrays.api.client.ApiCallback;
import io.northrays.api.client.ApiClient;
import io.northrays.api.client.ApiException;
import io.northrays.api.client.ApiResponse;
import io.northrays.api.client.Configuration;
import io.northrays.api.client.Pair;
import io.northrays.api.client.ProgressRequestBody;
import io.northrays.api.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.northrays.api.client.model.WebhookAppPortalAccess;
import io.northrays.api.client.model.WebhookInitializationStatus;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WebhooksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WebhooksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WebhooksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for webhookControllerGetAppPortalAccess
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> App Portal access generated successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerGetAppPortalAccessCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/organizations/{organizationId}/app-portal-access"
            .replace("{" + "organizationId" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call webhookControllerGetAppPortalAccessValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling webhookControllerGetAppPortalAccess(Async)");
        }

        return webhookControllerGetAppPortalAccessCall(organizationId, xNorthraysOrganizationID, _callback);

    }

    /**
     * Get Svix Consumer App Portal access for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return WebhookAppPortalAccess
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> App Portal access generated successfully </td><td>  -  </td></tr>
     </table>
     */
    public WebhookAppPortalAccess webhookControllerGetAppPortalAccess(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<WebhookAppPortalAccess> localVarResp = webhookControllerGetAppPortalAccessWithHttpInfo(organizationId, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Get Svix Consumer App Portal access for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;WebhookAppPortalAccess&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> App Portal access generated successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookAppPortalAccess> webhookControllerGetAppPortalAccessWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = webhookControllerGetAppPortalAccessValidateBeforeCall(organizationId, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<WebhookAppPortalAccess>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Svix Consumer App Portal access for an organization (asynchronously)
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> App Portal access generated successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerGetAppPortalAccessAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<WebhookAppPortalAccess> _callback) throws ApiException {

        okhttp3.Call localVarCall = webhookControllerGetAppPortalAccessValidateBeforeCall(organizationId, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<WebhookAppPortalAccess>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for webhookControllerGetInitializationStatus
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook initialization status </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerGetInitializationStatusCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/organizations/{organizationId}/initialization-status"
            .replace("{" + "organizationId" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call webhookControllerGetInitializationStatusValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling webhookControllerGetInitializationStatus(Async)");
        }

        return webhookControllerGetInitializationStatusCall(organizationId, xNorthraysOrganizationID, _callback);

    }

    /**
     * Get webhook initialization status for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return WebhookInitializationStatus
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook initialization status </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public WebhookInitializationStatus webhookControllerGetInitializationStatus(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<WebhookInitializationStatus> localVarResp = webhookControllerGetInitializationStatusWithHttpInfo(organizationId, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Get webhook initialization status for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;WebhookInitializationStatus&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook initialization status </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookInitializationStatus> webhookControllerGetInitializationStatusWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = webhookControllerGetInitializationStatusValidateBeforeCall(organizationId, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<WebhookInitializationStatus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get webhook initialization status for an organization (asynchronously)
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Webhook initialization status </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerGetInitializationStatusAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<WebhookInitializationStatus> _callback) throws ApiException {

        okhttp3.Call localVarCall = webhookControllerGetInitializationStatusValidateBeforeCall(organizationId, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<WebhookInitializationStatus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for webhookControllerInitializeWebhooks
     * @param organizationId Organization ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhooks initialized successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerInitializeWebhooksCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/organizations/{organizationId}/initialize"
            .replace("{" + "organizationId" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call webhookControllerInitializeWebhooksValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling webhookControllerInitializeWebhooks(Async)");
        }

        return webhookControllerInitializeWebhooksCall(organizationId, xNorthraysOrganizationID, _callback);

    }

    /**
     * Initialize webhooks for an organization
     * 
     * @param organizationId Organization ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return WebhookInitializationStatus
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhooks initialized successfully </td><td>  -  </td></tr>
     </table>
     */
    public WebhookInitializationStatus webhookControllerInitializeWebhooks(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        ApiResponse<WebhookInitializationStatus> localVarResp = webhookControllerInitializeWebhooksWithHttpInfo(organizationId, xNorthraysOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Initialize webhooks for an organization
     * 
     * @param organizationId Organization ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;WebhookInitializationStatus&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhooks initialized successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookInitializationStatus> webhookControllerInitializeWebhooksWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = webhookControllerInitializeWebhooksValidateBeforeCall(organizationId, xNorthraysOrganizationID, null);
        Type localVarReturnType = new TypeToken<WebhookInitializationStatus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Initialize webhooks for an organization (asynchronously)
     * 
     * @param organizationId Organization ID (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Webhooks initialized successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerInitializeWebhooksAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<WebhookInitializationStatus> _callback) throws ApiException {

        okhttp3.Call localVarCall = webhookControllerInitializeWebhooksValidateBeforeCall(organizationId, xNorthraysOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<WebhookInitializationStatus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for webhookControllerRefreshEndpoints
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Endpoint flag refreshed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerRefreshEndpointsCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/organizations/{organizationId}/refresh-endpoints"
            .replace("{" + "organizationId" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xNorthraysOrganizationID != null) {
            localVarHeaderParams.put("X-Northrays-Organization-ID", localVarApiClient.parameterToString(xNorthraysOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call webhookControllerRefreshEndpointsValidateBeforeCall(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling webhookControllerRefreshEndpoints(Async)");
        }

        return webhookControllerRefreshEndpointsCall(organizationId, xNorthraysOrganizationID, _callback);

    }

    /**
     * Refresh cached endpoint presence flag for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Endpoint flag refreshed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public void webhookControllerRefreshEndpoints(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        webhookControllerRefreshEndpointsWithHttpInfo(organizationId, xNorthraysOrganizationID);
    }

    /**
     * Refresh cached endpoint presence flag for an organization
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Endpoint flag refreshed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> webhookControllerRefreshEndpointsWithHttpInfo(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = webhookControllerRefreshEndpointsValidateBeforeCall(organizationId, xNorthraysOrganizationID, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Refresh cached endpoint presence flag for an organization (asynchronously)
     * 
     * @param organizationId  (required)
     * @param xNorthraysOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Endpoint flag refreshed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Webhook initialization status not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call webhookControllerRefreshEndpointsAsync(@javax.annotation.Nonnull String organizationId, @javax.annotation.Nullable String xNorthraysOrganizationID, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = webhookControllerRefreshEndpointsValidateBeforeCall(organizationId, xNorthraysOrganizationID, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
