#!/bin/bash
set -e

# Stop the service if it's running
if systemctl is-active --quiet northrays-runner.service; then
    systemctl stop northrays-runner.service
fi

# Disable the service
if systemctl is-enabled --quiet northrays-runner.service; then
    systemctl disable northrays-runner.service
fi

exit 0
