/*
Northrays

Northrays AI platform API Docs

API version: 1.0
Contact: support@northrays.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type ConfigAPI interface {

	/*
	ConfigControllerGetConfig Get config

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ConfigAPIConfigControllerGetConfigRequest
	*/
	ConfigControllerGetConfig(ctx context.Context) ConfigAPIConfigControllerGetConfigRequest

	// ConfigControllerGetConfigExecute executes the request
	//  @return NorthraysConfiguration
	ConfigControllerGetConfigExecute(r ConfigAPIConfigControllerGetConfigRequest) (*NorthraysConfiguration, *http.Response, error)
}

// ConfigAPIService ConfigAPI service
type ConfigAPIService service

type ConfigAPIConfigControllerGetConfigRequest struct {
	ctx context.Context
	ApiService ConfigAPI
}

func (r ConfigAPIConfigControllerGetConfigRequest) Execute() (*NorthraysConfiguration, *http.Response, error) {
	return r.ApiService.ConfigControllerGetConfigExecute(r)
}

/*
ConfigControllerGetConfig Get config

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ConfigAPIConfigControllerGetConfigRequest
*/
func (a *ConfigAPIService) ConfigControllerGetConfig(ctx context.Context) ConfigAPIConfigControllerGetConfigRequest {
	return ConfigAPIConfigControllerGetConfigRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return NorthraysConfiguration
func (a *ConfigAPIService) ConfigControllerGetConfigExecute(r ConfigAPIConfigControllerGetConfigRequest) (*NorthraysConfiguration, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *NorthraysConfiguration
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConfigAPIService.ConfigControllerGetConfig")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/config"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
