/*
 * Northrays
 * Northrays AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@northrays.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.api.client.api;

import io.northrays.api.client.ApiException;
import io.northrays.api.client.model.StorageAccessDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ObjectStorageApi
 */
@Disabled
public class ObjectStorageApiTest {

    private final ObjectStorageApi api = new ObjectStorageApi();

    /**
     * Get temporary storage access for pushing objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPushAccessTest() throws ApiException {
        String xNorthraysOrganizationID = null;
        StorageAccessDto response = api.getPushAccess(xNorthraysOrganizationID);
        // TODO: test validations
    }

}
