/*
 * Northrays
 * Northrays AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@northrays.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.api.client.api;

import io.northrays.api.client.ApiException;
import io.northrays.api.client.model.CreateVolume;
import io.northrays.api.client.model.VolumeDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VolumesApi
 */
@Disabled
public class VolumesApiTest {

    private final VolumesApi api = new VolumesApi();

    /**
     * Create a new volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVolumeTest() throws ApiException {
        CreateVolume createVolume = null;
        String xNorthraysOrganizationID = null;
        VolumeDto response = api.createVolume(createVolume, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVolumeTest() throws ApiException {
        String volumeId = null;
        String xNorthraysOrganizationID = null;
        api.deleteVolume(volumeId, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeTest() throws ApiException {
        String volumeId = null;
        String xNorthraysOrganizationID = null;
        VolumeDto response = api.getVolume(volumeId, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details by name
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeByNameTest() throws ApiException {
        String name = null;
        String xNorthraysOrganizationID = null;
        VolumeDto response = api.getVolumeByName(name, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * List all volumes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listVolumesTest() throws ApiException {
        String xNorthraysOrganizationID = null;
        Boolean includeDeleted = null;
        List<VolumeDto> response = api.listVolumes(xNorthraysOrganizationID, includeDeleted);
        // TODO: test validations
    }

}
