/*
 * Northrays
 * Northrays AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@northrays.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.api.client.api;

import io.northrays.api.client.ApiException;
import io.northrays.api.client.model.WebhookAppPortalAccess;
import io.northrays.api.client.model.WebhookInitializationStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Disabled
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    /**
     * Get Svix Consumer App Portal access for an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webhookControllerGetAppPortalAccessTest() throws ApiException {
        String organizationId = null;
        String xNorthraysOrganizationID = null;
        WebhookAppPortalAccess response = api.webhookControllerGetAppPortalAccess(organizationId, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Get webhook initialization status for an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webhookControllerGetInitializationStatusTest() throws ApiException {
        String organizationId = null;
        String xNorthraysOrganizationID = null;
        WebhookInitializationStatus response = api.webhookControllerGetInitializationStatus(organizationId, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Initialize webhooks for an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webhookControllerInitializeWebhooksTest() throws ApiException {
        String organizationId = null;
        String xNorthraysOrganizationID = null;
        WebhookInitializationStatus response = api.webhookControllerInitializeWebhooks(organizationId, xNorthraysOrganizationID);
        // TODO: test validations
    }

    /**
     * Refresh cached endpoint presence flag for an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webhookControllerRefreshEndpointsTest() throws ApiException {
        String organizationId = null;
        String xNorthraysOrganizationID = null;
        api.webhookControllerRefreshEndpoints(organizationId, xNorthraysOrganizationID);
        // TODO: test validations
    }

}
