/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Analytics API
 * Northrays Analytics API - Read-only telemetry and usage data. Authenticated via Northrays API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsMetricPoint
 */
export interface ModelsMetricPoint {
    /**
     * 
     * @type {string}
     * @memberof ModelsMetricPoint
     */
    'metricName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsMetricPoint
     */
    'timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsMetricPoint
     */
    'value'?: number;
}

