/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Analytics API
 * Northrays Analytics API - Read-only telemetry and usage data. Authenticated via Northrays API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsSpan
 */
export interface ModelsSpan {
    /**
     * 
     * @type {number}
     * @memberof ModelsSpan
     */
    'durationMs'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'parentSpanId'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ModelsSpan
     */
    'spanAttributes'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'spanId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'spanName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'statusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'statusMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsSpan
     */
    'traceId'?: string;
}

