/*
 * Northrays Toolbox API
 * Northrays Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Northrays API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Northrays Cloud: `https://proxy.app.northrays.com/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.northrays.toolbox.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Status
 */
public class StatusTest {
    /**
     * Model tests for Status
     */
    @Test
    public void testStatus() {
        // TODO: test Status
    }

}
