=begin
#Northrays Toolbox API

#Northrays Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Northrays API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Northrays Cloud: `https://proxy.app.northrays.com/toolbox/{sandboxId}`.

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'northrays_toolbox_api_client/api_client'
require 'northrays_toolbox_api_client/api_error'
require 'northrays_toolbox_api_client/api_model_base'
require 'northrays_toolbox_api_client/version'
require 'northrays_toolbox_api_client/configuration'

# Models
require 'northrays_toolbox_api_client/models/accessibility_bounds'
require 'northrays_toolbox_api_client/models/accessibility_invoke_request'
require 'northrays_toolbox_api_client/models/accessibility_node_request'
require 'northrays_toolbox_api_client/models/accessibility_nodes_response'
require 'northrays_toolbox_api_client/models/accessibility_set_value_request'
require 'northrays_toolbox_api_client/models/accessibility_tree_response'
require 'northrays_toolbox_api_client/models/chart'
require 'northrays_toolbox_api_client/models/chart_element'
require 'northrays_toolbox_api_client/models/code_run_artifacts'
require 'northrays_toolbox_api_client/models/code_run_request'
require 'northrays_toolbox_api_client/models/code_run_response'
require 'northrays_toolbox_api_client/models/command'
require 'northrays_toolbox_api_client/models/completion_context'
require 'northrays_toolbox_api_client/models/completion_item'
require 'northrays_toolbox_api_client/models/completion_list'
require 'northrays_toolbox_api_client/models/computer_use_accessibility_node'
require 'northrays_toolbox_api_client/models/computer_use_start_response'
require 'northrays_toolbox_api_client/models/computer_use_status_response'
require 'northrays_toolbox_api_client/models/computer_use_stop_response'
require 'northrays_toolbox_api_client/models/create_context_request'
require 'northrays_toolbox_api_client/models/create_session_request'
require 'northrays_toolbox_api_client/models/display_info'
require 'northrays_toolbox_api_client/models/display_info_response'
require 'northrays_toolbox_api_client/models/execute_request'
require 'northrays_toolbox_api_client/models/execute_response'
require 'northrays_toolbox_api_client/models/file_info'
require 'northrays_toolbox_api_client/models/file_status'
require 'northrays_toolbox_api_client/models/files_download_request'
require 'northrays_toolbox_api_client/models/find_accessibility_nodes_request'
require 'northrays_toolbox_api_client/models/git_add_request'
require 'northrays_toolbox_api_client/models/git_branch_request'
require 'northrays_toolbox_api_client/models/git_checkout_request'
require 'northrays_toolbox_api_client/models/git_clone_request'
require 'northrays_toolbox_api_client/models/git_commit_info'
require 'northrays_toolbox_api_client/models/git_commit_request'
require 'northrays_toolbox_api_client/models/git_commit_response'
require 'northrays_toolbox_api_client/models/git_delete_branch_request'
require 'northrays_toolbox_api_client/models/git_repo_request'
require 'northrays_toolbox_api_client/models/git_status'
require 'northrays_toolbox_api_client/models/initialize_request'
require 'northrays_toolbox_api_client/models/interpreter_context'
require 'northrays_toolbox_api_client/models/is_port_in_use_response'
require 'northrays_toolbox_api_client/models/keyboard_hotkey_request'
require 'northrays_toolbox_api_client/models/keyboard_press_request'
require 'northrays_toolbox_api_client/models/keyboard_type_request'
require 'northrays_toolbox_api_client/models/list_branch_response'
require 'northrays_toolbox_api_client/models/list_contexts_response'
require 'northrays_toolbox_api_client/models/list_recordings_response'
require 'northrays_toolbox_api_client/models/lsp_completion_params'
require 'northrays_toolbox_api_client/models/lsp_document_request'
require 'northrays_toolbox_api_client/models/lsp_location'
require 'northrays_toolbox_api_client/models/lsp_position'
require 'northrays_toolbox_api_client/models/lsp_range'
require 'northrays_toolbox_api_client/models/lsp_server_request'
require 'northrays_toolbox_api_client/models/lsp_symbol'
require 'northrays_toolbox_api_client/models/match'
require 'northrays_toolbox_api_client/models/mouse_click_request'
require 'northrays_toolbox_api_client/models/mouse_click_response'
require 'northrays_toolbox_api_client/models/mouse_drag_request'
require 'northrays_toolbox_api_client/models/mouse_drag_response'
require 'northrays_toolbox_api_client/models/mouse_move_request'
require 'northrays_toolbox_api_client/models/mouse_position_response'
require 'northrays_toolbox_api_client/models/mouse_scroll_request'
require 'northrays_toolbox_api_client/models/port_list'
require 'northrays_toolbox_api_client/models/position'
require 'northrays_toolbox_api_client/models/process_errors_response'
require 'northrays_toolbox_api_client/models/process_logs_response'
require 'northrays_toolbox_api_client/models/process_restart_response'
require 'northrays_toolbox_api_client/models/process_status'
require 'northrays_toolbox_api_client/models/process_status_response'
require 'northrays_toolbox_api_client/models/pty_create_request'
require 'northrays_toolbox_api_client/models/pty_create_response'
require 'northrays_toolbox_api_client/models/pty_list_response'
require 'northrays_toolbox_api_client/models/pty_resize_request'
require 'northrays_toolbox_api_client/models/pty_session_info'
require 'northrays_toolbox_api_client/models/recording'
require 'northrays_toolbox_api_client/models/replace_request'
require 'northrays_toolbox_api_client/models/replace_result'
require 'northrays_toolbox_api_client/models/screenshot_response'
require 'northrays_toolbox_api_client/models/scroll_response'
require 'northrays_toolbox_api_client/models/search_files_response'
require 'northrays_toolbox_api_client/models/session'
require 'northrays_toolbox_api_client/models/session_command_logs_response'
require 'northrays_toolbox_api_client/models/session_execute_request'
require 'northrays_toolbox_api_client/models/session_execute_response'
require 'northrays_toolbox_api_client/models/session_send_input_request'
require 'northrays_toolbox_api_client/models/start_recording_request'
require 'northrays_toolbox_api_client/models/status'
require 'northrays_toolbox_api_client/models/stop_recording_request'
require 'northrays_toolbox_api_client/models/user_home_dir_response'
require 'northrays_toolbox_api_client/models/window_info'
require 'northrays_toolbox_api_client/models/windows_response'
require 'northrays_toolbox_api_client/models/work_dir_response'

# APIs
require 'northrays_toolbox_api_client/api/computer_use_api'
require 'northrays_toolbox_api_client/api/file_system_api'
require 'northrays_toolbox_api_client/api/git_api'
require 'northrays_toolbox_api_client/api/info_api'
require 'northrays_toolbox_api_client/api/interpreter_api'
require 'northrays_toolbox_api_client/api/lsp_api'
require 'northrays_toolbox_api_client/api/port_api'
require 'northrays_toolbox_api_client/api/process_api'
require 'northrays_toolbox_api_client/api/server_api'

module NorthraysToolboxApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   NorthraysToolboxApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
