/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Billing API
 * Northrays Billing API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const BillingType = {
    BillingTypePrePaid: 'pre-paid',
    BillingTypePostPaid: 'post-paid',
} as const;

export type BillingType = typeof BillingType[keyof typeof BillingType];



