/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Billing API
 * Northrays Billing API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const InvoiceType = {
    InvoiceTypeSubscription: 'subscription',
    InvoiceTypeAddOn: 'add_on',
    InvoiceTypeOneOff: 'one_off',
} as const;

export type InvoiceType = typeof InvoiceType[keyof typeof InvoiceType];



