/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Toolbox API
 * Northrays Toolbox API. The base URL comes from the sandbox\'s `toolboxProxyUrl` field (returned in sandbox DTO by the main Northrays API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Northrays Cloud: `https://proxy.app.northrays.com/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FileInfo {
    'group': string;
    'isDir': boolean;
    /**
     * Deprecated: ModTime uses Go\'s time.String() layout which is not a standard format. Use ModifiedAt instead, which is serialized as ISO 8601 / RFC 3339.
     */
    'modTime': string;
    'mode': string;
    'modifiedAt': string;
    'name': string;
    'owner': string;
    'permissions': string;
    'size': number;
}

