/* tslint:disable */
/* eslint-disable */
/**
 * Northrays Toolbox API
 * Northrays Toolbox API. The base URL comes from the sandbox\'s `toolboxProxyUrl` field (returned in sandbox DTO by the main Northrays API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Northrays Cloud: `https://proxy.app.northrays.com/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FindAccessibilityNodesRequest {
    'limit'?: number;
    'name'?: string;
    /**
     * \"exact\" | \"substring\" | \"regex\"
     */
    'nameMatch'?: string;
    'pid'?: number;
    'role'?: string;
    'scope'?: string;
    'states'?: Array<string>;
}

